name: Remove unused imports

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install flake8 autoflake

      - name: Remove unused imports with autoflake
        run: |
          autoflake --remove-all-unused-imports --remove-unused-variables --in-place --recursive .

      - name: Capture removed imports
        id: removed_imports
        run: git diff --name-only --diff-filter=M && git diff > removed_imports_diff.txt

      - name: Commit changes if unused imports are removed
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add .
          git commit -m "Fix: Remove unused imports" || echo "No changes to commit"

      - name: Push changes and create pull request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: remove-unused-imports
          commit-message: Remove unused imports
          title: "Fix: Remove unused imports"
          body: |
            The following unused imports were removed:

            ```
            $(cat removed_imports_diff.txt)
            ```
